import agentV1Endpoint from "@/hono/api/agent-v1";
import agenticEndpoint from "@/hono/api/agentic";
import clientsEndpoint from "@/hono/api/clients";
import envelopePreparationEndpoint from "@/hono/api/envelope-preparation";
import envelopesEndpoint from "@/hono/api/envelopes";
import finalDocumentsEndpoint from "@/hono/api/final-documents";
import healthEndpoint from "@/hono/api/health";
import historyAccessEndpoint from "@/hono/api/history-access";
import historyCreatorEndpoint from "@/hono/api/history-creator";
import historyEnvelopeStartEndpoint from "@/hono/api/history-envelope-start";
import historyHumanReviewEndpoint from "@/hono/api/history-human-review";
import historySigningEndpoint from "@/hono/api/history-signing";
import modeNavigationEndpoint from "@/hono/api/mode-navigation";
import signingEndpoint from "@/hono/api/signing";
import { createHono } from "./factory";

export const apiHono = createHono().basePath("/api");

apiHono.route("/health", healthEndpoint);
apiHono.route("/agentic", agenticEndpoint);
apiHono.route("/v1", agentV1Endpoint);
apiHono.route("/history", historyAccessEndpoint);
apiHono.route("/history", historyCreatorEndpoint);
apiHono.route("/history", historyEnvelopeStartEndpoint);
apiHono.route("/history", historyHumanReviewEndpoint);
apiHono.route("/history", historySigningEndpoint);
apiHono.route("/navigate", modeNavigationEndpoint);
apiHono.route("/clients", clientsEndpoint);
apiHono.route("/envelopes", envelopesEndpoint);
apiHono.route("/envelopes", envelopePreparationEndpoint);
apiHono.route("/final-documents", finalDocumentsEndpoint);
apiHono.route("/signing", signingEndpoint);
