/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcePdfUploadRouteImport } from './routes/source-pdf-upload'
import { Route as ManualSigningSmokeRouteImport } from './routes/manual-signing-smoke'
import { Route as EnvelopeFieldsRouteImport } from './routes/envelope-fields'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SigningTokenRouteImport } from './routes/signing.$token'

const SourcePdfUploadRoute = SourcePdfUploadRouteImport.update({
  id: '/source-pdf-upload',
  path: '/source-pdf-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualSigningSmokeRoute = ManualSigningSmokeRouteImport.update({
  id: '/manual-signing-smoke',
  path: '/manual-signing-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvelopeFieldsRoute = EnvelopeFieldsRouteImport.update({
  id: '/envelope-fields',
  path: '/envelope-fields',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigningTokenRoute = SigningTokenRouteImport.update({
  id: '/signing/$token',
  path: '/signing/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/envelope-fields': typeof EnvelopeFieldsRoute
  '/manual-signing-smoke': typeof ManualSigningSmokeRoute
  '/source-pdf-upload': typeof SourcePdfUploadRoute
  '/signing/$token': typeof SigningTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/envelope-fields': typeof EnvelopeFieldsRoute
  '/manual-signing-smoke': typeof ManualSigningSmokeRoute
  '/source-pdf-upload': typeof SourcePdfUploadRoute
  '/signing/$token': typeof SigningTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/envelope-fields': typeof EnvelopeFieldsRoute
  '/manual-signing-smoke': typeof ManualSigningSmokeRoute
  '/source-pdf-upload': typeof SourcePdfUploadRoute
  '/signing/$token': typeof SigningTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/envelope-fields'
    | '/manual-signing-smoke'
    | '/source-pdf-upload'
    | '/signing/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/envelope-fields'
    | '/manual-signing-smoke'
    | '/source-pdf-upload'
    | '/signing/$token'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/envelope-fields'
    | '/manual-signing-smoke'
    | '/source-pdf-upload'
    | '/signing/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  EnvelopeFieldsRoute: typeof EnvelopeFieldsRoute
  ManualSigningSmokeRoute: typeof ManualSigningSmokeRoute
  SourcePdfUploadRoute: typeof SourcePdfUploadRoute
  SigningTokenRoute: typeof SigningTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/source-pdf-upload': {
      id: '/source-pdf-upload'
      path: '/source-pdf-upload'
      fullPath: '/source-pdf-upload'
      preLoaderRoute: typeof SourcePdfUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-signing-smoke': {
      id: '/manual-signing-smoke'
      path: '/manual-signing-smoke'
      fullPath: '/manual-signing-smoke'
      preLoaderRoute: typeof ManualSigningSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envelope-fields': {
      id: '/envelope-fields'
      path: '/envelope-fields'
      fullPath: '/envelope-fields'
      preLoaderRoute: typeof EnvelopeFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signing/$token': {
      id: '/signing/$token'
      path: '/signing/$token'
      fullPath: '/signing/$token'
      preLoaderRoute: typeof SigningTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  EnvelopeFieldsRoute: EnvelopeFieldsRoute,
  ManualSigningSmokeRoute: ManualSigningSmokeRoute,
  SourcePdfUploadRoute: SourcePdfUploadRoute,
  SigningTokenRoute: SigningTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
