/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgenticAccessRouteImport } from './routes/agentic-access'
import { Route as AgenticConsoleRouteImport } from './routes/agentic-console'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as EnvelopeFieldsRouteImport } from './routes/envelope-fields'
import { Route as ManualSigningSmokeRouteImport } from './routes/manual-signing-smoke'
import { Route as MyDocumentsRouteImport } from './routes/my-documents'
import { Route as NewDocumentRouteImport } from './routes/new-document'
import { Route as SourcePdfUploadRouteImport } from './routes/source-pdf-upload'
import { Route as CompletedDocumentsTokenRouteImport } from './routes/completed-documents.$token'
import { Route as HistoryAccessCredentialRouteImport } from './routes/history-access.$credential'
import { Route as HumanReviewReviewIdRouteImport } from './routes/human-review.$reviewId'
import { Route as MyDocumentsIndexRouteImport } from './routes/my-documents.index'
import { Route as MyDocumentsEnvelopeIdRouteImport } from './routes/my-documents.$envelopeId'
import { Route as SenderVerificationsTokenRouteImport } from './routes/sender-verifications.$token'
import { Route as SigningVerificationsTokenRouteImport } from './routes/signing-verifications.$token'
import { Route as SigningTokenRouteImport } from './routes/signing.$token'
import { Route as MyDocumentsEnvelopeIdIndexRouteImport } from './routes/my-documents.$envelopeId.index'
import { Route as MyDocumentsEnvelopeIdManageRouteImport } from './routes/my-documents.$envelopeId.manage'
import { Route as MyDocumentsEnvelopeIdSignRouteImport } from './routes/my-documents.$envelopeId.sign'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenticAccessRoute = AgenticAccessRouteImport.update({
  id: '/agentic-access',
  path: '/agentic-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenticConsoleRoute = AgenticConsoleRouteImport.update({
  id: '/agentic-console',
  path: '/agentic-console',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvelopeFieldsRoute = EnvelopeFieldsRouteImport.update({
  id: '/envelope-fields',
  path: '/envelope-fields',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualSigningSmokeRoute = ManualSigningSmokeRouteImport.update({
  id: '/manual-signing-smoke',
  path: '/manual-signing-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDocumentsRoute = MyDocumentsRouteImport.update({
  id: '/my-documents',
  path: '/my-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const NewDocumentRoute = NewDocumentRouteImport.update({
  id: '/new-document',
  path: '/new-document',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcePdfUploadRoute = SourcePdfUploadRouteImport.update({
  id: '/source-pdf-upload',
  path: '/source-pdf-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedDocumentsTokenRoute = CompletedDocumentsTokenRouteImport.update({
  id: '/completed-documents/$token',
  path: '/completed-documents/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryAccessCredentialRoute = HistoryAccessCredentialRouteImport.update({
  id: '/history-access/$credential',
  path: '/history-access/$credential',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanReviewReviewIdRoute = HumanReviewReviewIdRouteImport.update({
  id: '/human-review/$reviewId',
  path: '/human-review/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDocumentsIndexRoute = MyDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyDocumentsRoute,
} as any)
const MyDocumentsEnvelopeIdRoute = MyDocumentsEnvelopeIdRouteImport.update({
  id: '/$envelopeId',
  path: '/$envelopeId',
  getParentRoute: () => MyDocumentsRoute,
} as any)
const SenderVerificationsTokenRoute =
  SenderVerificationsTokenRouteImport.update({
    id: '/sender-verifications/$token',
    path: '/sender-verifications/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const SigningVerificationsTokenRoute =
  SigningVerificationsTokenRouteImport.update({
    id: '/signing-verifications/$token',
    path: '/signing-verifications/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const SigningTokenRoute = SigningTokenRouteImport.update({
  id: '/signing/$token',
  path: '/signing/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDocumentsEnvelopeIdIndexRoute =
  MyDocumentsEnvelopeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MyDocumentsEnvelopeIdRoute,
  } as any)
const MyDocumentsEnvelopeIdManageRoute =
  MyDocumentsEnvelopeIdManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => MyDocumentsEnvelopeIdRoute,
  } as any)
const MyDocumentsEnvelopeIdSignRoute =
  MyDocumentsEnvelopeIdSignRouteImport.update({
    id: '/sign',
    path: '/sign',
    getParentRoute: () => MyDocumentsEnvelopeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentic-access': typeof AgenticAccessRoute
  '/agentic-console': typeof AgenticConsoleRoute
  '/clients': typeof ClientsRoute
  '/envelope-fields': typeof EnvelopeFieldsRoute
  '/manual-signing-smoke': typeof ManualSigningSmokeRoute
  '/my-documents': typeof MyDocumentsRouteWithChildren
  '/new-document': typeof NewDocumentRoute
  '/source-pdf-upload': typeof SourcePdfUploadRoute
  '/completed-documents/$token': typeof CompletedDocumentsTokenRoute
  '/history-access/$credential': typeof HistoryAccessCredentialRoute
  '/human-review/$reviewId': typeof HumanReviewReviewIdRoute
  '/my-documents/$envelopeId': typeof MyDocumentsEnvelopeIdRouteWithChildren
  '/sender-verifications/$token': typeof SenderVerificationsTokenRoute
  '/signing-verifications/$token': typeof SigningVerificationsTokenRoute
  '/signing/$token': typeof SigningTokenRoute
  '/my-documents/': typeof MyDocumentsIndexRoute
  '/my-documents/$envelopeId/manage': typeof MyDocumentsEnvelopeIdManageRoute
  '/my-documents/$envelopeId/sign': typeof MyDocumentsEnvelopeIdSignRoute
  '/my-documents/$envelopeId/': typeof MyDocumentsEnvelopeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentic-access': typeof AgenticAccessRoute
  '/agentic-console': typeof AgenticConsoleRoute
  '/clients': typeof ClientsRoute
  '/envelope-fields': typeof EnvelopeFieldsRoute
  '/manual-signing-smoke': typeof ManualSigningSmokeRoute
  '/new-document': typeof NewDocumentRoute
  '/source-pdf-upload': typeof SourcePdfUploadRoute
  '/completed-documents/$token': typeof CompletedDocumentsTokenRoute
  '/history-access/$credential': typeof HistoryAccessCredentialRoute
  '/human-review/$reviewId': typeof HumanReviewReviewIdRoute
  '/sender-verifications/$token': typeof SenderVerificationsTokenRoute
  '/signing-verifications/$token': typeof SigningVerificationsTokenRoute
  '/signing/$token': typeof SigningTokenRoute
  '/my-documents': typeof MyDocumentsIndexRoute
  '/my-documents/$envelopeId/manage': typeof MyDocumentsEnvelopeIdManageRoute
  '/my-documents/$envelopeId/sign': typeof MyDocumentsEnvelopeIdSignRoute
  '/my-documents/$envelopeId': typeof MyDocumentsEnvelopeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentic-access': typeof AgenticAccessRoute
  '/agentic-console': typeof AgenticConsoleRoute
  '/clients': typeof ClientsRoute
  '/envelope-fields': typeof EnvelopeFieldsRoute
  '/manual-signing-smoke': typeof ManualSigningSmokeRoute
  '/my-documents': typeof MyDocumentsRouteWithChildren
  '/new-document': typeof NewDocumentRoute
  '/source-pdf-upload': typeof SourcePdfUploadRoute
  '/completed-documents/$token': typeof CompletedDocumentsTokenRoute
  '/history-access/$credential': typeof HistoryAccessCredentialRoute
  '/human-review/$reviewId': typeof HumanReviewReviewIdRoute
  '/my-documents/$envelopeId': typeof MyDocumentsEnvelopeIdRouteWithChildren
  '/sender-verifications/$token': typeof SenderVerificationsTokenRoute
  '/signing-verifications/$token': typeof SigningVerificationsTokenRoute
  '/signing/$token': typeof SigningTokenRoute
  '/my-documents/': typeof MyDocumentsIndexRoute
  '/my-documents/$envelopeId/manage': typeof MyDocumentsEnvelopeIdManageRoute
  '/my-documents/$envelopeId/sign': typeof MyDocumentsEnvelopeIdSignRoute
  '/my-documents/$envelopeId/': typeof MyDocumentsEnvelopeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentic-access'
    | '/agentic-console'
    | '/clients'
    | '/envelope-fields'
    | '/manual-signing-smoke'
    | '/my-documents'
    | '/new-document'
    | '/source-pdf-upload'
    | '/completed-documents/$token'
    | '/history-access/$credential'
    | '/human-review/$reviewId'
    | '/my-documents/$envelopeId'
    | '/sender-verifications/$token'
    | '/signing-verifications/$token'
    | '/signing/$token'
    | '/my-documents/'
    | '/my-documents/$envelopeId/manage'
    | '/my-documents/$envelopeId/sign'
    | '/my-documents/$envelopeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentic-access'
    | '/agentic-console'
    | '/clients'
    | '/envelope-fields'
    | '/manual-signing-smoke'
    | '/new-document'
    | '/source-pdf-upload'
    | '/completed-documents/$token'
    | '/history-access/$credential'
    | '/human-review/$reviewId'
    | '/sender-verifications/$token'
    | '/signing-verifications/$token'
    | '/signing/$token'
    | '/my-documents'
    | '/my-documents/$envelopeId/manage'
    | '/my-documents/$envelopeId/sign'
    | '/my-documents/$envelopeId'
  id:
    | '__root__'
    | '/'
    | '/agentic-access'
    | '/agentic-console'
    | '/clients'
    | '/envelope-fields'
    | '/manual-signing-smoke'
    | '/my-documents'
    | '/new-document'
    | '/source-pdf-upload'
    | '/completed-documents/$token'
    | '/history-access/$credential'
    | '/human-review/$reviewId'
    | '/my-documents/$envelopeId'
    | '/sender-verifications/$token'
    | '/signing-verifications/$token'
    | '/signing/$token'
    | '/my-documents/'
    | '/my-documents/$envelopeId/manage'
    | '/my-documents/$envelopeId/sign'
    | '/my-documents/$envelopeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenticAccessRoute: typeof AgenticAccessRoute
  AgenticConsoleRoute: typeof AgenticConsoleRoute
  ClientsRoute: typeof ClientsRoute
  EnvelopeFieldsRoute: typeof EnvelopeFieldsRoute
  ManualSigningSmokeRoute: typeof ManualSigningSmokeRoute
  MyDocumentsRoute: typeof MyDocumentsRouteWithChildren
  NewDocumentRoute: typeof NewDocumentRoute
  SourcePdfUploadRoute: typeof SourcePdfUploadRoute
  CompletedDocumentsTokenRoute: typeof CompletedDocumentsTokenRoute
  HistoryAccessCredentialRoute: typeof HistoryAccessCredentialRoute
  HumanReviewReviewIdRoute: typeof HumanReviewReviewIdRoute
  SenderVerificationsTokenRoute: typeof SenderVerificationsTokenRoute
  SigningVerificationsTokenRoute: typeof SigningVerificationsTokenRoute
  SigningTokenRoute: typeof SigningTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentic-access': {
      id: '/agentic-access'
      path: '/agentic-access'
      fullPath: '/agentic-access'
      preLoaderRoute: typeof AgenticAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentic-console': {
      id: '/agentic-console'
      path: '/agentic-console'
      fullPath: '/agentic-console'
      preLoaderRoute: typeof AgenticConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envelope-fields': {
      id: '/envelope-fields'
      path: '/envelope-fields'
      fullPath: '/envelope-fields'
      preLoaderRoute: typeof EnvelopeFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-signing-smoke': {
      id: '/manual-signing-smoke'
      path: '/manual-signing-smoke'
      fullPath: '/manual-signing-smoke'
      preLoaderRoute: typeof ManualSigningSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-documents': {
      id: '/my-documents'
      path: '/my-documents'
      fullPath: '/my-documents'
      preLoaderRoute: typeof MyDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-document': {
      id: '/new-document'
      path: '/new-document'
      fullPath: '/new-document'
      preLoaderRoute: typeof NewDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source-pdf-upload': {
      id: '/source-pdf-upload'
      path: '/source-pdf-upload'
      fullPath: '/source-pdf-upload'
      preLoaderRoute: typeof SourcePdfUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed-documents/$token': {
      id: '/completed-documents/$token'
      path: '/completed-documents/$token'
      fullPath: '/completed-documents/$token'
      preLoaderRoute: typeof CompletedDocumentsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history-access/$credential': {
      id: '/history-access/$credential'
      path: '/history-access/$credential'
      fullPath: '/history-access/$credential'
      preLoaderRoute: typeof HistoryAccessCredentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human-review/$reviewId': {
      id: '/human-review/$reviewId'
      path: '/human-review/$reviewId'
      fullPath: '/human-review/$reviewId'
      preLoaderRoute: typeof HumanReviewReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-documents/': {
      id: '/my-documents/'
      path: '/'
      fullPath: '/my-documents/'
      preLoaderRoute: typeof MyDocumentsIndexRouteImport
      parentRoute: typeof MyDocumentsRoute
    }
    '/my-documents/$envelopeId': {
      id: '/my-documents/$envelopeId'
      path: '/$envelopeId'
      fullPath: '/my-documents/$envelopeId'
      preLoaderRoute: typeof MyDocumentsEnvelopeIdRouteImport
      parentRoute: typeof MyDocumentsRoute
    }
    '/sender-verifications/$token': {
      id: '/sender-verifications/$token'
      path: '/sender-verifications/$token'
      fullPath: '/sender-verifications/$token'
      preLoaderRoute: typeof SenderVerificationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signing-verifications/$token': {
      id: '/signing-verifications/$token'
      path: '/signing-verifications/$token'
      fullPath: '/signing-verifications/$token'
      preLoaderRoute: typeof SigningVerificationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signing/$token': {
      id: '/signing/$token'
      path: '/signing/$token'
      fullPath: '/signing/$token'
      preLoaderRoute: typeof SigningTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-documents/$envelopeId/': {
      id: '/my-documents/$envelopeId/'
      path: '/'
      fullPath: '/my-documents/$envelopeId/'
      preLoaderRoute: typeof MyDocumentsEnvelopeIdIndexRouteImport
      parentRoute: typeof MyDocumentsEnvelopeIdRoute
    }
    '/my-documents/$envelopeId/manage': {
      id: '/my-documents/$envelopeId/manage'
      path: '/manage'
      fullPath: '/my-documents/$envelopeId/manage'
      preLoaderRoute: typeof MyDocumentsEnvelopeIdManageRouteImport
      parentRoute: typeof MyDocumentsEnvelopeIdRoute
    }
    '/my-documents/$envelopeId/sign': {
      id: '/my-documents/$envelopeId/sign'
      path: '/sign'
      fullPath: '/my-documents/$envelopeId/sign'
      preLoaderRoute: typeof MyDocumentsEnvelopeIdSignRouteImport
      parentRoute: typeof MyDocumentsEnvelopeIdRoute
    }
  }
}

interface MyDocumentsEnvelopeIdRouteChildren {
  MyDocumentsEnvelopeIdManageRoute: typeof MyDocumentsEnvelopeIdManageRoute
  MyDocumentsEnvelopeIdSignRoute: typeof MyDocumentsEnvelopeIdSignRoute
  MyDocumentsEnvelopeIdIndexRoute: typeof MyDocumentsEnvelopeIdIndexRoute
}

const MyDocumentsEnvelopeIdRouteChildren: MyDocumentsEnvelopeIdRouteChildren = {
  MyDocumentsEnvelopeIdManageRoute: MyDocumentsEnvelopeIdManageRoute,
  MyDocumentsEnvelopeIdSignRoute: MyDocumentsEnvelopeIdSignRoute,
  MyDocumentsEnvelopeIdIndexRoute: MyDocumentsEnvelopeIdIndexRoute,
}

const MyDocumentsEnvelopeIdRouteWithChildren =
  MyDocumentsEnvelopeIdRoute._addFileChildren(
    MyDocumentsEnvelopeIdRouteChildren,
  )

interface MyDocumentsRouteChildren {
  MyDocumentsEnvelopeIdRoute: typeof MyDocumentsEnvelopeIdRouteWithChildren
  MyDocumentsIndexRoute: typeof MyDocumentsIndexRoute
}

const MyDocumentsRouteChildren: MyDocumentsRouteChildren = {
  MyDocumentsEnvelopeIdRoute: MyDocumentsEnvelopeIdRouteWithChildren,
  MyDocumentsIndexRoute: MyDocumentsIndexRoute,
}

const MyDocumentsRouteWithChildren = MyDocumentsRoute._addFileChildren(
  MyDocumentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenticAccessRoute: AgenticAccessRoute,
  AgenticConsoleRoute: AgenticConsoleRoute,
  ClientsRoute: ClientsRoute,
  EnvelopeFieldsRoute: EnvelopeFieldsRoute,
  ManualSigningSmokeRoute: ManualSigningSmokeRoute,
  MyDocumentsRoute: MyDocumentsRouteWithChildren,
  NewDocumentRoute: NewDocumentRoute,
  SourcePdfUploadRoute: SourcePdfUploadRoute,
  CompletedDocumentsTokenRoute: CompletedDocumentsTokenRoute,
  HistoryAccessCredentialRoute: HistoryAccessCredentialRoute,
  HumanReviewReviewIdRoute: HumanReviewReviewIdRoute,
  SenderVerificationsTokenRoute: SenderVerificationsTokenRoute,
  SigningVerificationsTokenRoute: SigningVerificationsTokenRoute,
  SigningTokenRoute: SigningTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
